### ISSUE TITLE
Bill Murray image is broken

### ISSUE THREAD

**Issue by djesernik** [leucos/ansible-tuto-demosite#4]
The site that is used for providing Bill Murray placeholder photos, http://www.fillmurray.com/, has moved to the www subdomain, breaking the image from rendering.

https://github.com/leucos/ansible-tuto-demosite/blob/9b309f637bc4ecc4f4cda10523cb60cd5da9edcf/index.php#L11 just needs to be updated with a `www.` added for it to work again.
` <img src="http://www.fillmurray.com/408/287" /> `

**Comment by leucos** [comment]
Thanks for the report !
Would you like to create a pull request for this ?

**Comment by djesernik** [comment]
Sure thing. This is my first PR from a forked repo, so let me know if I'm missing anything.
https://github.com/leucos/ansible-tuto-demosite/pull/5

**Comment by leucos** [comment]
Awesome ! This is perfect. Thank you very much :+1:
